#!/usr/bin/env bash
FREEFALL_PORT=3000 \
FREEFALL_LOG_LEVEL=DEBUG \
PGUSER=freefall \
PGPASSWORD=freefall \
PGDATABASE=freefall \
DALIPECHE_ADDRESS=10.20.1.130 \
DALIPECHE_PORT=3001 \
DALIPECHE_API_KEY=8yKZ8eIWxA401K6p \
FREEFALL_STDOUT_FILE=/opt/freefall/logs/server_stdout.log \
FREEFALL_STDERR_FILE=/opt/freefall/logs/server_stderr.log \
FREEFALL_PROFILING_ON=true \
PROFILING_EL_EMIT_INTERVAL=60000 \
PROFILING_EL_LATENCY_CHECK_INTERVAL=10 \
pm2 start ./server.js -i max

