FREEFALL_PORT=3000 \
FREEFALL_LOG_LEVEL=DEBUG \
PGUSER=freefall \
PGPASSWORD=freefall \
PGDATABASE=freefall \
DALIPECHE_ADDRESS=10.20.1.130 \
DALIPECHE_PORT=3001 \
DALIPECHE_API_KEY=8yKZ8eIWxA401K6p \
pm2 start ./server.js -i max

